pipeline{
    agent any 
     parameters {
        choice(name: 'ENVIRONMENT', choices: ['dev', 'stage'], description: 'Target environment')
    }
    stages{
            stage('Cleanup') {
            steps {
                cleanWs()
            }
        }
        Stage('checkout SCM'{
            steps{
               sh 'ls -ltr'          
               // git branch: 'main' ,url: 'https://github.com/Yaathvik2020/practice-branch.git'
            }
        }
        stage('terraform run'){
            steps{
                withCredentials([[
                    $class: 'AmazonWebServicesCredentialsBinding',
                    credentialsId: 'aws-creds'
                ]]) {
            dir('tf-resources-ec2'){
                sh 'terraform init -input=false'
                sh 'terraform plan -out=tfplan -input=false'
                sh 'terraform apply -input=false -auto-approve tfplan'
            }
            }
        }
        }
        stage('destroy'){
            steps{
            withCredentials([[
                    $class: 'AmazonWebServicesCredentialsBinding',
                    credentialsId: 'aws-creds'
                ]]) {
            dir('tf-resources-ec2'){
                sh 'terraform destroy -input=false -auto-approve'
            }
            }
        }
    }
}
post {
        success {
            echo 'Infra applied successfully.'
             cleanWs()
        }
        failure {
            echo 'Something went wrong.'
            cleanWs()
        }
    }
}
